# -*- mode: ruby -*-
# vi: set ft=ruby :
$install_docker = <<-SCRIPT
  apt-get update
  apt-get install ca-certificates curl -y
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt-get update
  apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
SCRIPT

$configure_docker = <<-SCRIPT
echo '{"insecure-registries" : ["gitlab.local:5001", "gitlab.local:8888"]}' > /etc/docker/daemon.json
sed -i "/ExecStart/ s/$/  -H tcp:\\/\\\/0.0.0.0:2375/" /lib/systemd/system/docker.service && systemctl daemon-reload && systemctl restart docker
echo "172.40.0.2 gitlab.local" >> /etc/hosts
SCRIPT


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20231027.0.0"
  config.vm.network "private_network", ip: "192.168.56.150"
  config.vm.hostname = "bootcampVM"  
  config.vm.define "bootcampVM"
  #config.vagrant.plugins = ["vagrant-vbguest"]
  config.vm.provider "virtualbox" do |vb|
  vb.name = "bootcampVM"
  vb.memory = "6144"
  vb.cpus = 4
  end
  # add swap
  config.vm.provision :shell, inline: "fallocate -l 4G /swapfile && chmod 0600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' >> /etc/fstab"
  config.vm.provision :shell, inline: "echo vm.swappiness = 10 >> /etc/sysctl.conf && echo vm.vfs_cache_pressure = 50 >> /etc/sysctl.conf && sysctl -p"
  config.vm.provision "file", source: "gitlab", destination: "$HOME/"
  config.vm.provision "shell", inline: $install_docker
  config.vm.provision "shell", inline: $configure_docker
  config.vm.provision "shell", inline: "cd gitlab; docker compose up -d"
  config.vm.provision "shell", inline: "cd gitlab; /bin/bash runner_register.sh" 
end
