apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: sqldata
        persistentVolumeClaim:
          claimName: mypvc
      containers:
      - name: mysql
        image: mysql
        envFrom:
        - configMapRef:
            name: mysql
        ports:
        - containerPort: 3306
          name: sql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: sqldata
        
