apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic
  labels:
    name: nginx
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: dynamicpvc
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: data
      mountPath: /testpv
