apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamicpvc
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
