apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      run: counter
  template:
    metadata:
      labels:
        run: counter
    spec:
      containers:
      - image: dockercampusmvp/go-hello-world
        name: counter
        env:
        - name: FOO3
          value: BAR3
        - name: _ENV
          valueFrom:
            configMapKeyRef:
              key: environment
              name: myconfig
        envFrom:
        - configMapRef:
            name: myconfig