#  kubectl create secret generic mysecret --dry-run=client -o yaml --from-file config.json --from-file config2.txt | kubectl apply -f -


apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      run: counter
  template:
    metadata:
      labels:
        run: counter
    spec:
      volumes:
      - name: files
        configMap:
          name: config
      - name: standard
        configMap:
          name: standard
      - name: secrets
        secret:
          secretName: mysecret
      containers:
      - image: dockercampusmvp/go-hello-world
        name: counter
        volumeMounts:
        - name: files
          mountPath: /data
        - name: secrets
          mountPath: /data-secret
        - name: standard
          mountPath: /data-standard


# Una opción para montar un secreto y un cm juntos es usar un volumen proyectado
# https://kubernetes.io/docs/concepts/storage/projected-volumes/