variables:
  PYTHON_VERSION: "3.8"
  BASE_VERSION: "20.04"
  BASE_IMAGE_NAME: "ubuntu"
  REGISTRY_PATH: "$CI_REGISTRY/$CI_PROJECT_PATH"

stages:
  - docker:build


docker:build:
  stage: docker:build
  before_script:
     - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN  $REGISTRY_PATH
  script:
    - docker build --build-arg base_image_name=$BASE_IMAGE_NAME --build-arg python_version=$PYTHON_VERSION --build-arg base_version=$BASE_VERSION -t $REGISTRY_PATH:$CI_COMMIT_TAG .
    - docker push $REGISTRY_PATH:$CI_COMMIT_TAG
    - echo "Pushed $IREGISTRY_PATH:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG
    
