version: "3.9" 
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root_pwd
       MYSQL_DATABASE: wpdb
       MYSQL_USER: wp_user
       MYSQL_PASSWORD: wp_pwd
     networks: 
        - wordpress-network
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
      - wordpress_data:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wp_user
       WORDPRESS_DB_PASSWORD: wp_pwd
       WORDPRESS_DB_NAME: wpdb
     networks: 
       - wordpress-network
volumes:
    db_data: 
    wordpress_data: 
networks:
    wordpress-network: 