apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    name: nginx
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: nginxdata
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: data
      mountPath: /testpv
