apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  storageClassName: lemoncoder
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0002/
