apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxdata2
spec:
  storageClassName: lemoncoder
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
