#Imagen que voy a utilizar como base
FROM nginx:alpine

#Etiquetado
LABEL maintainer="gisela.torres@returngis.net"

#Modificaciones sobre la imagen que he utilizado como base, en este caso alpine
COPY content/ /usr/share/nginx/html/