apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnet
  template:
    metadata:
      labels:
        app: aspnet
    spec:
      containers:
      - name: web
        image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: aspnet-svc
spec:
  type: LoadBalancer
  selector:
    app: aspnet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
