apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
    component: backend
    team: ultra
spec:
  containers:
  - name: mysql
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "patata"
    - name: MYSQL_USER
      value: "wp"
    - name: MYSQL_PASSWORD
      value: "patata"
    - name: MYSQL_DATABASE
      value: "wp"