stages:
    - stage1
    - stage2
    - stage3
    - stage4


job1:
    stage: stage1
    script:
      - echo "${CI_JOB_STAGE} - ${CI_JOB_NAME}" > artifact.txt
    artifacts:
        paths:
            - artifact.txt

job2:
    stage: stage1
    script:
      - echo "${CI_JOB_STAGE} - ${CI_JOB_NAME}"
      - sleep 10
      - ls -la
    needs:
        - job: job1
          artifacts: false

job3:
    stage: stage2
    script:
      - echo "${CI_JOB_STAGE} - ${CI_JOB_NAME}"
      - sleep 5
      - ls -la
      - cat artifact.txt
    needs:
        - job: job1
          artifacts: true # Este es el valor por defecto (no hace falta especificar)

job4:
    stage: stage3
    script:
      - echo "${CI_JOB_STAGE} - ${CI_JOB_NAME}"
      - ls -la
    needs:
        - job: job3
          artifacts: false

job5:
    stage: stage4
    script:
      - echo "${CI_JOB_STAGE} - ${CI_JOB_NAME}"
      - ls -la
    needs: []
