include:
  - project: 'bootcamp/test_includes'
    ref: master
    file: 'variables.yml'
  - project: 'bootcamp/test_includes'
    ref: master
    file: 'extend_image.yml'
  - project: 'bootcamp/test_includes'
    ref: master
    file: 'jobs/build.yml'
  - project: 'bootcamp/test_includes'
    ref: master
    file: 'jobs/before_script.yml'


stages:
  - build

build-job:
    stage: build
    extends: .image
    rules:
        - if: $CI_COMMIT_TAG