services:
  frontend:
    build:
      context: ./frontend
    deploy:
      replicas: 1
    ports:
      - 3000:8080
    profiles: [frontend]

  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    profiles: [debug]

  mongodb:
    image: mongo:latest
