services:
  frontend:
    build:
      context: ./frontend
    deploy:
      replicas: 1
    ports:
      - 3000:8080
    profiles: [frontend]

  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    profiles: [debug]
    # environment:
    #   - DEBUG=${DEBUG}
    env_file:
      - path: ./default.env
        required: true
      - path: ./override.env
        required: false

  mongodb:
    image: mongo:latest
